### ISSUE TITLE
Can not wear Dragon Square Shield without completing the Legends Guild quest

### ISSUE THREAD

**Issue by Kenix3** [Marwolf/Open-RSC#31]
Message when attempting to wear Dragon Square without completing the quest:
you have not earned the right to wear this yet
you need to complete the legend's guild quest
[defense level]

Begs the question of if we should implement this for the legends cape. The original game didn't stop you because the cape is non-tradable.

**Comment by Marwolf** [comment]
legends cape should be handed once #16 is done.

**Comment by Kenix3** [comment]
Agreed to keep it like original RSC. Let #16 handle it.
